"""initial tables

Revision ID: 5042b72a795e
Revises: 
Create Date: 2026-02-22 22:22:12.899075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5042b72a795e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.String(), nullable=True),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('date_utc', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category_key', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('posted_chat_id', sa.String(), nullable=True),
    sa.Column('posted_message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_content_hash'), 'messages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_source_chat_id'), 'messages', ['source_chat_id'], unique=False)
    op.create_index(op.f('ix_messages_source_message_id'), 'messages', ['source_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_source_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_source_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_content_hash'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
